id: medcom.fhir.dk.carecommunication
canonical: http://medcomfhir.dk/ig/carecommunication
name: MedComCarecommunication
title: "DK MedCom Carecommunication"
description: The DK MedCom Carecommunication IG
status: draft
version: "3.0.0"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: draft
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 
    uri: https://hl7.dk/fhir/core/2.0.0/
    version: 2.0.0
  medcom.fhir.dk.core: 2.1.0
  medcom.fhir.dk.messaging: 2.0.0
  medcom.fhir.dk.terminology: 1.3.0
  
menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
